//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateDentalClinic.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.HistoryAppointments = new HashSet<HistoryAppointment>();
        }
    
        public int AppointmentID { get; set; }
        public System.TimeSpan BeginTimeAppointment { get; set; }
        public System.TimeSpan EndTimeAppointment { get; set; }
        public System.DateTime DateAppointment { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> StatusAppointmentID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> ServiceID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Service Service { get; set; }
        public virtual StatusAppointment StatusAppointment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryAppointment> HistoryAppointments { get; set; }
    }
}
