//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateDentalClinic.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryAppointment
    {
        public int HistoryAppointmentID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> AppointmentsAppointmentID { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Client Client { get; set; }
    }
}
