//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateDentalClinic.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DentalClinicEntities : DbContext
    {
        private static DentalClinicEntities _context;
        public DentalClinicEntities()
            : base("name=DentalClinicEntities")
        {
        }

        public static DentalClinicEntities GetContext()
        {
            if (_context == null)
            {
                _context = new DentalClinicEntities();
            }

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<HistoryAppointment> HistoryAppointments { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Specialization> Specializations { get; set; }
        public virtual DbSet<StatusAppointment> StatusAppointments { get; set; }
        public virtual DbSet<WorkSchedule> WorkSchedules { get; set; }
    }
}
