//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateDentalClinic.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkSchedule
    {
        public int WorkScheduleID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan BeginWorkDay { get; set; }
        public System.TimeSpan EndWorkDay { get; set; }
        public Nullable<int> DoctorID { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
